# Signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name": "teste",
  "email": "teste@gmail.com",
  "password": "123456",
  "role": "NORMAL",
  "cpf": "22233344466"
}

###
# Login

POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "matheus@gmail.com",
  "password": "123456"
}

###
# Get Address by CEP

GET http://localhost:3003/user/address/33333050

###
# Add User Address

POST http://localhost:3003/user/address
Content-Type: application/json

{
  "cep": "33025010",
  "numero": 123,
  "complemento": "casa",
  "userEmail": "matheus@gmail.com"
}

###
# Add New Products

POST http://localhost:3003/product/create
Content-Type: application/json

{
  "name": "Mouse óptico",
  "price": 127.32,
  "image_url": "https://i.zst.com.br/thumbs/12/1e/16/1724303697.jpg"
}

###
# Add New Purchase

POST http://localhost:3003/purchase/create
Content-Type: application/json

{
  "user_id": "4ab0de2b-1467-441b-8dcb-b399a1730c1c",
  "product_id": "01f82be2-baf3-4925-994e-66ab39d39eee",
  "quantity": 5,
  "total_price": 636.6
}
